class_name GameInfo

enum {
	EVENT_NONE,

	# delta events
	EVENT_DELTA_BLOCK_REPLACE,

	# player events
	EVENT_PLAYER_SHOOT,
	EVENT_PLAYER_BLOCK_BREAK,
	EVENT_PLAYER_BLOCK_PLACE,
	EVENT_PLAYER_BLOCK_BREAK_DELTA,
	EVENT_PLAYER_BLOCK_PLACE_DELTA,
	EVENT_PLAYER_BLOCK_SET_FIRE,

	# ???
	EVENT_CHAT_MESSAGE,
}
